fix: fixing deploy workflow

diff --git a/.github/workflows/cd-deploy.yml b/.github/workflows/cd-deploy.yml
--- a/.github/workflows/cd-deploy.yml
+++ b/.github/workflows/cd-deploy.yml
@@ -16,10 +16,16 @@ jobs:
       uses: actions/checkout@v2
 
     # Step 2: Set up SSH connection to DigitalOcean VM
-    - name: Set up SSH
-      uses: webfactory/ssh-agent@v0.5.3
-      with:
-        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+    - name: Copy SSH Key
+      run: |
+        mkdir -p ~/.ssh  # Ensure the .ssh directory exists
+        if ! grep -q "${{ secrets.SSH_PUBLIC_KEY }}" ~/.ssh/authorized_keys; then
+          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
+        else
+          echo "not found the secret"
+        fi
+        chmod 600 ~/.ssh/authorized_keys  # Set the correct permissions
+
 
     # Step 3: Deploy to DigitalOcean VM
     - name: Deploy to DigitalOcean
